version: "2"
services:
  web:  #Container Service Name
    build: .            #For Current DIR Dockerfile
    #build: ./Dir_name   #For Parent  DIR Dockerfile
    image: technbd/my-java-app
    container_name: my-java-app
    ports:
      - "8084:8080"

